### PR TITLE
Fixes divide by zero exception when w.ratio = 0

### PR DESCRIPTION
**Pull request by 8o7wer**
I have no idea what the code does, this might fuck shit up, but I edited my local copy of the file with these changes and it fixed a divide by zero issue I would get randomly.

### CODE REVIEW

**Comment by faiface** [comment]
Weird that it would be zero. I could add some comments there, but the ratio value is a way to work correctly on the hiDPI screens. When you create a window, it first checks whether its size in pixels is the same as the requested size. If it's not, it calculates the ratio of difference, stores that and resizes the window appropriately.

The ratio of 0 would mean that the actual size is smaller than the requested size, which is kind of weird.

Could you investigate a bit when this happens and whether your drawing works correctly (whether the bounds are where they should be, etc)?

This certainly needs a fix, but I feel like there's a deeper issue.

**Comment by 8o7wer** [comment]
Sure, I can post code and look into it myself a bit when I get home tonight.

**Comment by 8o7wer** [comment]
Alright, not home but I figured it out. The issue happens when you make a window larger than the monitor size.

**Comment by faiface** [comment]
Thanks for finding the reason! So, since, w.ratio is also used later in code, the proper fix will be to make it so that it's at least 1. This can be done simply by checking its value right after setting it and fixing it if it's less than 1.

**Comment by 8o7wer** [comment]
No problem. I didnt see any other uses of it in my quick readthrough of the code so I didnt bother throwing a min(w.ratio, 1) in there.

**Pull request closed without merging**
